[tool.poetry]
name = "decentralized"
version = "0.1.0"
description = "Implementation of decentralized potential iLQR for cooperative multi-agent navigation."
authors = ["Zach Williams <zjwilliams20@gmail.com>"]

[tool.poetry.dependencies]
python = "~3.10"
numpy = "^1.22.4"
scipy = "^1.8.1"
matplotlib = "^3.5.2"
ipympl = "^0.9.1"
jupyter = "^1.0.0"
scikit-learn = "^1.1.1"
torch = {url = "https://download.pytorch.org/whl/cpu/torch-1.11.0%2Bcpu-cp310-cp310-linux_x86_64.whl"}

[tool.poetry.dev-dependencies]
sympy = "^1.10.1"
seaborn = "^0.11.2"
jupyterlab = "^3.4.3"
jupyterlab-git = "^0.37.1"
jupyterlab-horizon-theme = "^3.0.1"
flake8 = "^4.0.1"
black = "^22.3.0"
networkx = "^2.8.4"
py-spy = "^0.3.12"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
